<a href="https://colab.research.google.com/github/wahyukusuma/NFRSentimentAnalysis/blob/master/Binary_Relevance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

In [0]:
#Input Training Instances
lines = [line.rstrip('\n') for line in open('C:/Users/Nishant/Desktop/560/6000/Binary Classification/Data Only + Sentiment.txt','r',  encoding="utf8")]
dataset = np.array(lines)

In [0]:
#Input Label of Training Instances
with open('C:/Users/Nishant/Desktop/560/6000/Binary Classification/Label.txt', 'r') as f:
    labels  = []
    for line in f:
        a= line.rstrip('\n').split(',')
        labels.append(list(filter(None, a)))

In [0]:
#Using Scikit Learn In-built Split Functionality
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state = 1)

In [0]:
#Extract Labels for each class for Training Set
from sklearn import preprocessing

#Mentioning Class name preserves order
mlb = preprocessing.MultiLabelBinarizer(classes=("Dep", "Per", "Sup", "Usa", "Mis"))
Y_train = mlb.fit_transform(y_train)
Training_Labels_Dep = [row[0] for row in Y_train]
Training_Labels_Per = [row[1] for row in Y_train]
Training_Labels_Sup = [row[2] for row in Y_train]
Training_Labels_Usa = [row[3] for row in Y_train]

#print(X_train)

In [0]:
#Extract Labels for each class for Test Set
from sklearn import preprocessing
mlb = preprocessing.MultiLabelBinarizer(classes=("Dep", "Per", "Sup", "Usa", "Mis"))
Y_test = mlb.fit_transform(y_test)
Test_Labels_Dep = [row[0] for row in Y_test]
Test_Labels_Per = [row[1] for row in Y_test]
Test_Labels_Sup = [row[2] for row in Y_test]
Test_Labels_Usa = [row[3] for row in Y_test]

In [0]:
import nltk
from nltk import word_tokenize     
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()
def stem_tokens(tokens, stemmer):
    stemmed = []
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

def tokenize(text):
    tokens = nltk.word_tokenize(text)
    stems = stem_tokens(tokens, stemmer)
    return stems

# Initialize the `count_vectorizer` 
#count_vectorizer = CountVectorizer(lowercase='true')
#count_vectorizer = CountVectorizer(tokenizer=tokenize, lowercase='true')
count_vectorizer = CountVectorizer(tokenizer=tokenize, stop_words='english', lowercase='true')

# Fit and transform the training data 
count_train = count_vectorizer.fit_transform(X_train) 

# Transform the test set 
count_test = count_vectorizer.transform(X_test)

# Initialize the `tfidf_vectorizer` 
#tfidf_vectorizer = TfidfVectorizer(lowercase='true') 
tfidf_vectorizer = TfidfVectorizer(tokenizer=tokenize, use_idf = False, lowercase='true') 
#tfidf_vectorizer = TfidfVectorizer(tokenizer=tokenize, stop_words='english', lowercase='true') 

# Fit and transform the training data 
tfidf_train = tfidf_vectorizer.fit_transform(X_train) 

# Transform the test set 
tfidf_test = tfidf_vectorizer.transform(X_test)

from sklearn.svm import SVC
SVC_Classifier =  OneVsRestClassifier(SVC(kernel='linear'))

from sklearn.naive_bayes import MultinomialNB
NB_Classifier = MultinomialNB()

classifier = SVC_Classifier
print(classifier)

classifier.fit(count_train, Training_Labels_Dep)
P_Dep = (classifier.predict(count_test))

classifier.fit(count_train, Training_Labels_Per)
P_Per = classifier.predict(count_test)

classifier.fit(count_train, Training_Labels_Sup)
P_Sup = classifier.predict(count_test)

classifier.fit(count_train, Training_Labels_Usa)
P_Usa = classifier.predict(count_test)

OneVsRestClassifier(estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
          n_jobs=1)


In [0]:
classifier.fit(count_train, Training_Labels_Dep)
predicted2 = classifier.predict(count_test2)
print(predicted2)

classifier.fit(count_train, Training_Labels_Per)
predicted2 = classifier.predict(count_test2)
print(predicted2)

classifier.fit(count_train, Training_Labels_Sup)
predicted2 = classifier.predict(count_test2)
print(predicted2)

classifier.fit(count_train, Training_Labels_Usa)
predicted2 = classifier.predict(count_test2)
print(predicted2)

[0 0]
[0 0]
[1 0]
[0 0]


In [0]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import fbeta_score
from sklearn.metrics import confusion_matrix

print ("Precision: Dep",precision_score(Test_Labels_Dep,P_Dep))
print ("Recall: Dep",recall_score(Test_Labels_Dep,P_Dep))
print("\n")

print ("Precision: Per",precision_score(Test_Labels_Per,P_Per))
print ("Recall: Per",recall_score(Test_Labels_Per,P_Per))
print("\n")

print ("Precision: Sup",precision_score(Test_Labels_Sup,P_Sup))
print ("Recall: Sup",recall_score(Test_Labels_Sup,P_Sup))

print("\n")

print ("Precision: Usa",precision_score(Test_Labels_Usa,P_Usa))
print ("Recall: Usa",recall_score(Test_Labels_Usa,P_Usa))

Average_Precision = (precision_score(Test_Labels_Dep,P_Dep) + precision_score(Test_Labels_Per,P_Per) + \
                    precision_score(Test_Labels_Sup,P_Sup) + precision_score(Test_Labels_Usa,P_Usa)) / 4.0

Average_Recall = (recall_score(Test_Labels_Dep,P_Dep) + recall_score(Test_Labels_Per,P_Per) + \
                    recall_score(Test_Labels_Sup,P_Sup) + recall_score(Test_Labels_Usa,P_Usa)) / 4.0


Precision: Dep 0.656934306569
Recall: Dep 0.578778135048


Precision: Per 0.678571428571
Recall: Per 0.59375


Precision: Sup 0.590909090909
Recall: Sup 0.469879518072


Precision: Usa 0.55593220339
Recall: Usa 0.459383753501


In [0]:
print (Average_Precision)
print (Average_Recall)

0.62058675736
0.525447851655


In [0]:
combined_Actual_labels = np.zeros((len(P_Dep), 4))
for i in range(len(P_Dep)):
    if Test_Labels_Dep[i] == 1:
        combined_Actual_labels[i][0]=1
    if Test_Labels_Per[i] == 1:
        combined_Actual_labels[i][1]=1
    if Test_Labels_Sup[i] == 1:
        combined_Actual_labels[i][2]=1
    if Test_Labels_Usa[i] == 1:
        combined_Actual_labels[i][3]=1

combined_Predictions = np.zeros((len(P_Dep), 4))
for i in range(len(P_Dep)):
    if P_Dep[i] == 1:
        combined_Predictions[i][0]=1
    if P_Per[i] == 1:
        combined_Predictions[i][1]=1
    if P_Sup[i] == 1:
        combined_Predictions[i][2]=1
    if P_Usa[i] == 1:
        combined_Predictions[i][3]=1

print(combined_Actual_labels)
print(combined_Predictions)

[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 ..., 
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]]


In [0]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import hamming_loss

y_true = combined_Actual_labels
y_pred = combined_Predictions

def hamming_score(y_true, y_pred, normalize=True, sample_weight=None):
    acc_list = []
    for i in range(y_true.shape[0]):
        set_true = set( np.where(y_true[i])[0] )
        set_pred = set( np.where(y_pred[i])[0] )
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred))/\
                    float( len(set_true.union(set_pred)) )
        acc_list.append(tmp_a)
    return np.mean(acc_list)

if __name__ == "__main__":
    print('Hamming score: {0}'.format(hamming_score(y_true, y_pred)))

    import sklearn.metrics

    #print('Subset accuracy: {0}'.format(accuracy_score(y_true, y_pred, normalize=True, sample_weight=None)))
    #print('Hamming loss: {0}'.format(hamming_loss(y_true, y_pred)))

Hamming score: 0.7080555555555555
Subset accuracy: 0.6711111111111111
Hamming loss: 0.09902777777777778


In [0]:
#Compute Hamming Scored for 4 Categories only

number_of_non_miscellaneous = 0
for i in range(len(combined_Actual_labels)):
    if np.sum(combined_Actual_labels[i]) > 0:
        number_of_non_miscellaneous = number_of_non_miscellaneous + 1

#Create two new arrays with Labels excluding non-miscellaneous
combined_Actual_labels_non_miscellaneous = np.zeros((number_of_non_miscellaneous, 4))
combined_Predicted_labels_non_miscellaneous = np.zeros((number_of_non_miscellaneous, 4))

counter = -1
for j in range(len(combined_Actual_labels)):
    if(np.sum(combined_Actual_labels[j]) > 0):
        counter = counter + 1
        combined_Actual_labels_non_miscellaneous[counter]= combined_Actual_labels[j]
        combined_Predicted_labels_non_miscellaneous[counter] = combined_Predictions[j]  

In [0]:
print('Hamming score: {0}'.format(hamming_score(combined_Actual_labels_non_miscellaneous, combined_Predicted_labels_non_miscellaneous)))
print('Subset accuracy: {0}'.format(sklearn.metrics.accuracy_score(combined_Actual_labels_non_miscellaneous, combined_Predicted_labels_non_miscellaneous, normalize=True, sample_weight=None)))
print('Hamming loss: {0}'.format(sklearn.metrics.hamming_loss(combined_Actual_labels_non_miscellaneous, combined_Predicted_labels_non_miscellaneous)))

Hamming score: 0.4695121951219512
Subset accuracy: 0.3794037940379404
Hamming loss: 0.19139566395663957
